# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hobby_name', models.CharField(max_length=32, verbose_name='Название хобби')),
                ('hobby_desc', models.CharField(blank=True, max_length=32, verbose_name='Описание хобби')),
                ('hobby_period', models.PositiveIntegerField(blank=True, verbose_name='Как давно увлекаюсь')),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_of_study', models.CharField(max_length=32, verbose_name='Место учёбы')),
                ('discipline', models.CharField(max_length=32, verbose_name='Дисциполина')),
            ],
        ),
    ]
