# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-16 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_hobby_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='study_period',
            field=models.PositiveIntegerField(default=3, verbose_name='Время обучения'),
        ),
    ]
