# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-17 09:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_hobby_hobby_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='study',
            name='study_period',
        ),
        migrations.RemoveField(
            model_name='work',
            name='period',
        ),
    ]
